/** Numeric-only protocol shared by the optional collection kernel and the
 * inspection subpath. Public counter/detail strings stay in inspection.ts. */
export const COLLECTION_ROW_INTENTS_STAGED = 35
export const COLLECTION_ROW_INTENT_STORAGE_ALLOCATIONS = 36
export const COLLECTION_ROW_FINAL_RESOLUTION_VISITS = 37
export const COLLECTION_ROW_ROUTE_VISITS = 38
export const COLLECTION_MEMBERSHIP_RECORD_CREATIONS = 39
export const COLLECTION_MEMBERSHIP_ROUTE_VISITS = 40
export const COLLECTION_MEMBERSHIP_ROWS_SCANNED = 41
export const COLLECTION_MEMBERSHIP_ARRAY_ALLOCATIONS = 42
export const COLLECTION_ROW_SOURCES_CHANGED = 43
export const COLLECTION_MEMBERSHIP_SOURCES_CHANGED = 44
export const COLLECTION_EFFECTIVE_DELTAS_PREPARED = 45
export const COLLECTION_OWNER_RETENTION_SETS_CREATED = 46
export const COLLECTION_OWNER_RETAINS = 47
export const COLLECTION_OWNER_RELEASES = 48

export const COLLECTION_INTENT_SET = 64
export const COLLECTION_INTENT_UPDATE = 65
export const COLLECTION_INTENT_RESET = 66
export const COLLECTION_INTENT_DELETE = 67
export const COLLECTION_EFFECTIVE_INSERT = 68
export const COLLECTION_EFFECTIVE_UPDATE = 69
export const COLLECTION_EFFECTIVE_REMOVE = 70
export const COLLECTION_MEMBERSHIP_INSERT = 71
export const COLLECTION_MEMBERSHIP_REMOVE = 72
export const COLLECTION_ROW_PUBLISHED = 73
export const COLLECTION_MEMBERSHIP_PUBLISHED = 74
export const COLLECTION_ROW_MATERIALIZED = 75
export const COLLECTION_MEMBERSHIP_MATERIALIZED = 76
