name: Publish Docs
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - name: Install
              run: bun install
            - name: Build Packages
              run: bun run build
              env:
                  NODE_ENV: production
            - name: Build Docs
              run: bun run docs:build
              working-directory: ./packages/documentation
              env:
                  NODE_ENV: production
            - name: Upload website artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "packages/documentation/docs/dist"
    deploy:
        needs: build
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
