name: Publish Docs
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.13
            - name: Install
              run: bun install --frozen-lockfile
            - name: Build Docs
              run: bun run docs:build
              env:
                  NODE_ENV: production
                  PUBLIC_POSTHOG_KEY: ${{ vars.PUBLIC_POSTHOG_KEY }}
            - name: Upload website artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: "docs/dist"
    deploy:
        needs: build
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
